removed nmap dependency

diff --git a/check_ssl_cert b/check_ssl_cert
--- a/check_ssl_cert
+++ b/check_ssl_cert
@@ -151,107 +151,94 @@ fi
 #######################
 # Check needed programs
 
-check_prog nmap
-NMAP=$PROG
-
 check_prog openssl
 OPENSSL=$PROG
 
 ################################################################################
-# check if the port is open
-if $NMAP $HOST -P0 -sT -p $PORT 2>&1 | grep -q open ; then
+# fetch the X.509 certificate
 
-    ################################################################################
-    # fetch the X.509 certificate
+CERT="/tmp/check_certs-out.$$"
+ERROR="/tmp/check_certs-errors.$$"
 
-    CERT="/tmp/check_certs-out.$$"
-    ERROR="/tmp/check_certs-errors.$$"
+echo 'Q' | $OPENSSL s_client -connect $HOST:$PORT 2> ${ERROR} 1> ${CERT}
 
-    echo 'Q' | $OPENSSL s_client -connect $HOST:$PORT 2> ${ERROR} 1> ${CERT}
-
-    if grep -q "Connection refused" ${ERROR} ; then
-        rm -f ${CERT} ${ERROR}
-        critical "connection refused"
-        return
-    fi
-
-    ################################################################################
-    # parse the X.509 certificate
-
-    CA=`$OPENSSL x509 -in ${CERT} -issuer -noout | sed -e "s/.*\/O=//" | sed -r "s/\/[A-Z]+=.*//"`
-    DATE=`$OPENSSL x509 -in ${CERT} -enddate -noout | sed "s/notAfter\=//"`
-
-    ################################################################################
-    # check the issuer
-
-    if [ -n "$ISSUER" ] ; then
-        if ! echo $CA | grep -q "^$ISSUER$" ; then
-            critical "invalid CA ($ISSUER does not match $CA)"
-        fi
-    fi
-
-    ################################################################################
-    # check the validity
-
-    if [ -n "$DAYS" ] ; then
-
-        if ! echo $DAYS | grep -q [1-9][0-9]* ; then
-            critical "invalid number of days ($DAYS)"
-        fi
-
-        DIFF=$((`date -d "$DATE" "+%s"` - `date "+%s"`))
-        DAYS=$((DAYS * 86400))
-
-        if [ $DIFF -le 0 ] ; then
-            critical "certificate is expired (was valid until $DATE)"
-        fi
-
-        if [ $DIFF -le $DAYS ] ; then
-            MESSAGE=`format_days $DIFF`
-            MESSAGE=`echo "certificate is exipring in" $MESSAGE`
-            warning "$MESSAGE"
-        fi
-          
-    fi
-
-    ################################################################################
-    # check the organization
-
-    if [ -n "$ORGANIZATION" ] ; then
-
-        ORG=`$OPENSSL x509 -in ${CERT} -subject -noout | sed -e "s/.*\/O=//" | sed -e "s/\/.*//"`
-
-        if ! echo $ORG | grep -q "^$ORGANIZATION" ; then
-            critical "invalid organization ($ORGANIZATION does not match $ORG)"
-        fi
-
-    fi
-
-    ################################################################################
-    # check the organization
-
-    if [ -n "$ADDR" ] ; then
-
-        EMAIL=`$OPENSSL x509 -in ${CERT} -email -noout`
-
-        if ! echo $EMAIL | grep -q "^$ADDR" ; then
-            critical "invalid email ($ADDR does not match $EMAIL)"
-        fi
-
-    fi
-    
-    ################################################################################
-    # clean up
+if grep -q "Connection refused" ${ERROR} ; then
     rm -f ${CERT} ${ERROR}
+    critical "connection refused ($HOST:$PORT)"
+    return
+fi
 
-    echo "SSL CERT OK - X.509 certificate from $CA valid until $DATE"
-    
-    cleanup;
+################################################################################
+# parse the X.509 certificate
 
-    exit 0
-    
-else
+CA=`$OPENSSL x509 -in ${CERT} -issuer -noout | sed -e "s/.*\/O=//" | sed -r "s/\/[A-Z]+=.*//"`
+DATE=`$OPENSSL x509 -in ${CERT} -enddate -noout | sed "s/notAfter\=//"`
 
-    critical "$HOST:$PORT closed"
+################################################################################
+# check the issuer
+
+if [ -n "$ISSUER" ] ; then
+    if ! echo $CA | grep -q "^$ISSUER$" ; then
+        critical "invalid CA ($ISSUER does not match $CA)"
+    fi
+fi
+
+################################################################################
+# check the validity
+
+if [ -n "$DAYS" ] ; then
+
+    if ! echo $DAYS | grep -q [1-9][0-9]* ; then
+        critical "invalid number of days ($DAYS)"
+    fi
+
+    DIFF=$((`date -d "$DATE" "+%s"` - `date "+%s"`))
+    DAYS=$((DAYS * 86400))
+
+    if [ $DIFF -le 0 ] ; then
+        critical "certificate is expired (was valid until $DATE)"
+    fi
+
+    if [ $DIFF -le $DAYS ] ; then
+        MESSAGE=`format_days $DIFF`
+        MESSAGE=`echo "certificate is exipring in" $MESSAGE`
+        warning "$MESSAGE"
+    fi
+      
+fi
+
+################################################################################
+# check the organization
+
+if [ -n "$ORGANIZATION" ] ; then
+
+    ORG=`$OPENSSL x509 -in ${CERT} -subject -noout | sed -e "s/.*\/O=//" | sed -e "s/\/.*//"`
+
+    if ! echo $ORG | grep -q "^$ORGANIZATION" ; then
+        critical "invalid organization ($ORGANIZATION does not match $ORG)"
+    fi
 
 fi
+
+################################################################################
+# check the organization
+
+if [ -n "$ADDR" ] ; then
+
+    EMAIL=`$OPENSSL x509 -in ${CERT} -email -noout`
+
+    if ! echo $EMAIL | grep -q "^$ADDR" ; then
+        critical "invalid email ($ADDR does not match $EMAIL)"
+    fi
+
+fi
+
+################################################################################
+# clean up
+rm -f ${CERT} ${ERROR}
+
+echo "SSL CERT OK - X.509 certificate from $CA valid until $DATE"
+
+cleanup;
+
+exit 0
