Finalized the changes about timeout and TLS

diff --git a/check_ssl_cert b/check_ssl_cert
--- a/check_ssl_cert
+++ b/check_ssl_cert
@@ -102,12 +102,17 @@ timeout() {
 
     # start the command in a subshell to avoid problem with pipes
     # (spawn accepts one command)
-    command="sh -c \"$2\""
+    command="/bin/sh -c \"$2\""
 
-    expect -c "set echo \"-noecho\"; set timeout $time; spawn -noecho $command; expect timeout { exit 1 } eof { exit 0 }"
+    if [ -n "${EXPECT}" ] ; then
+        expect -c "set echo \"-noecho\"; set timeout $time; spawn -noecho $command; expect timeout { exit 1 } eof { exit 0 }"    
 
-    if [ $? = 1 ] ; then
-        critical "Timeout after $TIMEOUT seconds"
+        if [ $? = 1 ] ; then
+            critical "Timeout after $TIMEOUT seconds"
+        fi
+
+    else
+        eval ${command}
     fi
             
 }
@@ -116,7 +121,8 @@ timeout() {
 # Checks if a given program is available and executable
 # Params
 #   $1 program name
-check_prog() {
+# Returns 1 if the program exists and is executable
+check_required_prog() {
 
     PROG=$(which $1)
 
@@ -168,8 +174,13 @@ fi
 #######################
 # Check needed programs
 
-check_prog openssl
+check_required_prog openssl
 OPENSSL=$PROG
+
+EXPECT=$(which expect)
+if [ -z "${EXPECT}" -a -n "${VERBOSE}" ] ; then
+    echo "Expect not found: disabling timeouts"
+fi
 
 ################################################################################
 # fetch the X.509 certificate
