add support for certificate check inside jks-files

diff --git a/check_ssl_cert b/check_ssl_cert
--- a/check_ssl_cert
+++ b/check_ssl_cert
@@ -341,6 +341,8 @@ usage() {
     echo "      --init-host-cache            Initialize the host cache"
     echo "      --issuer-cert-cache dir      Directory where to store issuer"
     echo "                                   certificates cache"
+    echo "      --jks-alias alias            alias name of the Java KeyStore entry"
+    echo "                                   (requires --file)"
     # Delimiter at 78 chars ############################################################
     echo "   -K,--clientkey path             Use client certificate key to authenticate"
     # Delimiter at 78 chars ############################################################
@@ -843,12 +845,12 @@ hours_until() {
         # Warning: some shell script formatting tools will indent the EOF! (should be at position 0)
         if ! HOURS_UNTIL=$(
             perl - "${DATE}" <<-"EOF"
-				                    use strict;
-				                    use warnings;
-				                    use Date::Parse;
-				                    my $cert_date = str2time( $ARGV[0] );
-				                    my $hours = int (( $cert_date - time ) / 3600 + 0.5);
-				                    print "$hours\n";
+                                    use strict;
+                                    use warnings;
+                                    use Date::Parse;
+                                    my $cert_date = str2time( $ARGV[0] );
+                                    my $hours = int (( $cert_date - time ) / 3600 + 0.5);
+                                    print "$hours\n";
 EOF
         ); then
             # something went wrong with the embedded Perl code: check the indentation of EOF
@@ -2534,6 +2536,17 @@ fetch_certificate() {
                     unknown "Error converting ${FILE}: ${CONVERSION_ERROR_TMP}"
                 fi
 
+            elif [ -n "${JKSALIAS}" ] && "${FILE_BIN}" -L -b "${FILE}" | grep -q -E 'KeyStore|data'; then
+
+                debuglog 'converting JKS to PEM'
+                check_required_prog 'keytool'
+                KEYTOOLBIN=${PROG}
+                "${KEYTOOLBIN}" -exportcert -rfc -keystore "${FILE}" -alias "${JKSALIAS}" -file "${CERT}" -storepass "${PASSWORD_SOURCE}" &>"${CONVERSION_ERROR}"
+
+                if [ $? -eq 1 ]; then
+                    unknown "Error converting JKS to PEM: $(head -n 1 "${CONVERSION_ERROR}") "
+                fi
+
             elif "${FILE_BIN}" -L -b "${FILE}" | "${GREP_BIN}" -q -E '(data|Certificate)'; then
 
                 debuglog 'converting DER to PEM'
@@ -3331,7 +3344,12 @@ parse_command_line_options() {
             INETPROTO="-$2"
             shift 2
             ;;
-        --nmap-bin)
+        --jks-alias)
+            check_option_argument '--jks-alias' "$2"
+            JKSALIAS="$2"
+            shift 2
+            ;;
+       --nmap-bin)
             check_option_argument '--nmap-bin' "$2"
             NMAP_BIN="$2"
             shift 2
